POST http://localhost:8080/create/acount
Content-Type: application/json

{
  "name": "Gabriel",
  "cpf": "05371957341"
}

###

GET http://localhost:8080/statement/05371957341

###

GET http://localhost:8080/statement/date?date=2022-12-30
Content-Type: application/json